0it [00:00, ?it/s]
0it [00:00, ?it/s]

Traceback (most recent call last):
  File "/Users/ruolinsu/anaconda3/envs/dstqa/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/training/trainer_pieces.py", line 42, in from_params
    all_datasets = training_util.datasets_from_params(params, cache_directory, cache_prefix)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/training/util.py", line 178, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 134, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 134, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "./dstqa/dstqa_reader.py", line 61, in _read
    file_path = cached_path(file_path)
  File "/Users/ruolinsu/anaconda3/envs/dstqa/lib/python3.6/site-packages/allennlp/common/file_utils.py", line 106, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file ./data/train.json not found
